version: '3'

services:
    db:
        image: 'postgres:11'
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
    # app:
    #     container_name: next-app
    #     stdin_open: true
    #     restart: always
    #     depends_on:
    #         - db
    #     build:
    #         context: ./
    #         dockerfile: Dockerfile.dev
    #     ports:
    #         - 3000:3000
    #     environment:
    #         - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?schema=public
